"""Data Briefs: one-tap compilation of verified analysis into a shareable report.

Generalizes Autopilot's auto-compile: verified agent cells are preferred,
then pinned cells, then recent narrated cells. The resulting report reuses
the existing Reports pipeline (editor + public share page) unchanged.
"""

from __future__ import annotations

import logging

logger = logging.getLogger("DataBriefs")

_MAX_BRIEF_BLOCKS = 12


def select_brief_cells(cells: list[dict]) -> list[dict]:
    """Pick the most valuable cells for a brief: verified > pinned > narrated."""
    candidates = [
        c for c in cells or [] if c.get("type") == "code" and not c.get("failed")
    ]
    verified = [c for c in candidates if c.get("agent_answered") and c.get("verified")]
    pinned = [c for c in candidates if c.get("pinned")]
    narrated = [
        c
        for c in candidates
        if (c.get("narration") or c.get("description")) and c not in verified
    ]
    ordered: list[dict] = []
    seen: set[int] = set()
    for group in (verified, pinned, narrated):
        for cell in group:
            key = id(cell)
            if key not in seen:
                seen.add(key)
                ordered.append(cell)
    return ordered[:_MAX_BRIEF_BLOCKS]


def brief_title(dataset_name: str) -> str:
    stem = (dataset_name or "Analysis").rsplit(".", 1)[0]
    return f"Data Brief: {stem}"


async def compile_brief_async(
    report_service,
    project_id: str,
    cells: list[dict],
    dataset_name: str,
) -> dict | None:
    """Compile notable cells into a new Report; returns the report or None."""
    from services.report_service import build_report_block_from_cell

    chosen = select_brief_cells(cells)
    if not chosen:
        return None

    blocks = [build_report_block_from_cell(c) for c in chosen]
    # Drop blocks with nothing to show. Text-only VERIFIED answers count:
    # their narration IS the finding.
    blocks = [
        b
        for b in blocks
        if b.get("figure_png_b64")
        or b.get("stdout")
        or b.get("serialized_result")
        or b.get("description")
    ]
    if not blocks:
        return None

    return await report_service.create_report(
        title=brief_title(dataset_name),
        dataset_name=dataset_name,
        blocks=blocks,
        description=(
            f"Auto-compiled from {len(blocks)} verified analysis step(s) "
            f"on {dataset_name}."
        ),
    )


def brief_to_html(report: dict) -> bytes:
    """Serialize a report into a standalone styled HTML document.

    Saved to Downloads; opens in any browser where print-to-PDF works —
    giving mobile users a deliverable without an in-app rendering engine.
    """
    esc = lambda s: (
        str(s or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
    parts = [
        "<!doctype html><html><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        "<title>",
        esc(report.get("title", "Data Brief")),
        (
            "</title><style>body{font-family:system-ui,sans-serif;margin:24px;"
            "max-width:760px;color:#1a1a1a}h1{font-size:1.5rem}h3{margin:18px 0 6px}"
            ".desc{color:#555}.pre{background:#f4f4f6;padding:10px;border-radius:8px;"
            "overflow:auto;font-size:12px;white-space:pre-wrap}img{max-width:100%;"
            "border-radius:8px}.tag{display:inline-block;background:#e0f2f1;"
            "color:#00695c;padding:2px 10px;border-radius:999px;font-size:12px}"
            ".footer{margin-top:28px;color:#888;font-size:12px}</style></head><body>"
        ),
        "<h1>",
        esc(report.get("title", "Data Brief")),
        "</h1>",
        "<span class='tag'>",
        esc(report.get("dataset_name", "")),
        "</span><p class='desc'>",
        esc(report.get("description", "")),
        "</p>",
    ]
    for i, block in enumerate(report.get("blocks", []), start=1):
        parts.append(f"<h3>{i}. {esc(block.get('prompt', 'Step'))}</h3>")
        desc = block.get("description") or block.get("narration")
        if desc:
            parts.append(f"<p>{esc(desc)}</p>")
        png = block.get("figure_png_b64")
        if png:
            parts.append(f"<img src='data:image/png;base64,{png}' alt='chart {i}'/>")
        ser = block.get("serialized_result")
        if isinstance(ser, dict) and ser.get("png_b64"):
            parts.append(
                f"<img src='data:image/png;base64,{ser['png_b64']}' alt='chart {i}'/>"
            )
        stdout = block.get("stdout")
        if stdout:
            parts.append(f"<div class='pre'>{esc(stdout[:2000])}</div>")

    parts.append(
        "<p class='footer'>Generated by SpanInsight · verified against "
        "executed results</p></body></html>"
    )
    return "".join(parts).encode("utf-8")
