name: Recover Keystore

on:
  workflow_dispatch: # This allows you to run the workflow manually from a button

jobs:
  recover-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Decode and Save Keystore
        # This pipes the secret directly into the decode command and saves the binary file
        run: echo "${{ secrets.YOUR_SECRET_NAME }}" | base64 --decode > recovered_keystore.jks

      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-signing-key
          path: recovered_keystore.jks
          retention-days: 1 # Automatically deletes from GitHub after 1 day
