name: Recover Keystore

on:
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > spaninsight_github_keystore.jks

      - name: Extract Info
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "Alias: $KEY_ALIAS" > keystore_info.txt

      - name: Upload Keystore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spaninsight-keystore-artifact
          path: |
            spaninsight_github_keystore.jks
            keystore_info.txt
          retention-days: 1
